### ISSUE TITLE
UserProfile.getSubprofile() only returns 1 subprofile, and may even break.

### ISSUE THREAD

**Issue by amedranogil** [universAAL/ontology#3]

**Comment by Alfiva** [comment]
I have the weird feeling I already looked into this, and it is not as easy as it may seem... I hope I am wrong, I will get to it when I have a moment

**Comment by Alfiva** [comment]
OK so it was not such a critical thing after all. It's just that the getter/setter is simply made considering a 1:1 property (functional). I will change the methods to treat it as a 0:N property. In fact, all classes in ont.profile use getters/setters with this 1:1 consideration, so I will have to review them all to fix the 0:N ones.

**Comment by amedranogil** [comment]
while we are on this topic, I have spend the better part of the last weeks implementing and reimplementing the if (it_is_a_list) thing...
we aught to do something to make this easier, and it is one simple thing that can be done very quickly that will improve a lot the usability of universAAL data representation. I remember discussing this back at the uR-team the rationale behind not doing this was that the root data class (Resource) was already too heavy. 
Maybe we can pick up that discussion, my proposal was to split it into different classes each adding different functionally and at the end of the subclass chain keep Resource, this will ensure compatibility while cleaning the code

**Comment by Alfiva** [comment]
I realized my last comment was on the code of User.getUserProfile, which is OK, because it is a functional property. I cannot find UserProfile.getSubprofile() in ont.profile though. Where is it?

**Comment by amedranogil** [comment]
I mean https://github.com/universAAL/ontology/blob/2dd627c6a1dbbdd8db17f3ccc43c2dae9ba8a199/ont.profile/src/main/java/org/universAAL/ontology/profile/Profile.java

getter + setter for subprofileS for a Profile.

**Comment by Alfiva** [comment]
Done in 4b43667. (Thanks to ont.cryptographic for the copy/pasted methods ;) )
[https://github.com/universAAL/ontology/commit/4b43667fea6ea4f0fdbcd203966a4264c055aa33](url)
