### ISSUE TITLE
Measurement prefixes use incorrect URIs in ont.unit

### ISSUE THREAD

**Issue by Alfiva** [universAAL/ontology#482]
I am not sure if this has been spotted before, or if it's a gotcha that has to work this way, but measurement prefixes do not follow our proper URI format and namespace, instead being things like just `<mega>` or `<kilo>` instead of `<http://ontology.universaal.org/Unit.owl#kilo>` (you can see this directly here: http://ontology.universaal.org/Unit.ttl ).
If this is indeed a bug, the problem is located in ont.unit, in InternationalSystem.java:74, where it creates the enumeration of prefixes with the constructor of Prefix. This constructor in Prefix.java:36 takes the parameter and uses it as URI directly, unlike in Unit.java, which prepends the uAAL namespace.
This can be solved by either prepending the namespace in Prefix constructor, or doing it when calling it in InternationalSystem.

**Comment by amedranogil** [comment]
yes, this is a Bug.
units should be instances, and they should have fully qualified URIs, prefix should have the same behavior of Unit.

**Comment by Alfiva** [comment]
I can fix it myself, since I have it in front of me right now. My only concern is that everyone is aware that this changes the measurement ontology URIs of the prefixes. Not sure how many people use those, but they will change and be incompatible with previous versions.
